pipeline {
    agent any

    stages {

        stage('Build') {
            steps {
                dir('14-jenkins-zabbix-cicd-monitoring') {
                    sh 'echo "Build Stage Completed"'
                }
            }
        }

        stage('Test') {
            steps {
                dir('14-jenkins-zabbix-cicd-monitoring') {
                    sh 'chmod +x test.sh'
                    sh './test.sh'
                }
            }
        }

        stage('Deploy') {
            steps {
                dir('14-jenkins-zabbix-cicd-monitoring') {
                    sh 'docker build -t jenkins-demo .'
                    sh 'docker rm -f jenkins-demo || true'
                    sh 'docker run -d --name jenkins-demo -p 3000:3000 jenkins-demo'
                }
            }
        }
    }
}
